name: 'Deploy to Dev'

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  deploy:
    runs-on: windows-2016

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Add nuget
        uses: nuget/setup-nuget@v1
        with:
           nuget-version: '5.x'

      - name: nuget restore
        run: nuget restore dotnet-aspmvc5-v1/BeanstalkDotNetSample.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3

      - name: MSBuild
        run: msbuild dotnet-aspmvc5-v1/MVC5App/MVC5App.csproj /p:TargetFrameworkVersion=v4.5.2 /p:Configuration=Release /p:DeployIisAppPath="Default Web Site" /p:PackageAsSingleFile=false /t:Package
        shell: cmd

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dotnet-aspmvc5-v1
